name: CI Pipeline - Quality & Tests

on:
  push:
    branches:
      - main  # Uniquement lors des push/merge vers main
  pull_request:
    branches:
      - main  # PRs vers main (branches en review)
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache uv binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/uv
          key: uv-binary-${{ runner.os }}

      - name: Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-packages-${{ runner.os }}-${{ hashFiles('10_preprod/uv.lock') }}
          restore-keys: |
            uv-packages-${{ runner.os }}-

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: 10_preprod/.venv
          key: venv-quality-v3-${{ runner.os }}-py3.13-${{ hashFiles('10_preprod/uv.lock') }}

      - name: Install uv
        run: |
          if ! command -v uv &> /dev/null; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Install dev dependencies (PREPROD)
        run: |
          cd 10_preprod
          # Créer un symlink /app/40_utils pour que le path absolu dans pyproject.toml fonctionne
          sudo mkdir -p /app
          sudo ln -s "$(pwd)/../40_utils" /app/40_utils
          if [ ! -d .venv ]; then
            uv venv
          fi
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Check PEP8 compliance with flake8
        run: |
          cd 10_preprod
          source .venv/bin/activate
          echo "=== Vérification PEP8 avec flake8 (PREPROD) ==="
          flake8 src/ tests/ --config=../.flake8 --statistics --count

      - name: Check code formatting with black
        run: |
          cd 10_preprod
          source .venv/bin/activate
          echo "=== Vérification du formatage avec black (PREPROD) ==="
          black --check --diff src/ tests/

      - name: Check docstrings with pydocstyle
        run: |
          cd 10_preprod
          source .venv/bin/activate
          echo "=== Vérification des docstrings avec pydocstyle (PREPROD) ==="
          pydocstyle src/ --config=../.pydocstyle
        continue-on-error: true  # Ne bloque pas si les docstrings manquent (warning)

      - name: Type checking with mypy
        run: |
          cd 10_preprod
          source .venv/bin/activate
          echo "=== Vérification des types avec mypy (PREPROD) ==="
          mypy src/ --ignore-missing-imports || true
        continue-on-error: true  # Type checking optionnel pour le moment

  # DÉSACTIVÉ: PROD est maintenant un artifact généré par deploy_preprod_to_prod.sh
  # Les tests se font uniquement sur PREPROD qui est la source de vérité
  # test-prod:
  #   name: Tests unitaires - Production (DÉSACTIVÉ - artifact)
  #   runs-on: ubuntu-latest
  #   needs: quality-checks
  #   steps:
  #     - name: Skip PROD tests
  #       run: echo "PROD est un artifact, tests sur PREPROD uniquement"

  test-preprod:
    name: Tests unitaires - Preprod (coverage >= 90%)
    runs-on: ubuntu-latest
    needs: quality-checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache uv binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/uv
          key: uv-binary-${{ runner.os }}

      - name: Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-packages-${{ runner.os }}-${{ hashFiles('10_preprod/uv.lock') }}
          restore-keys: |
            uv-packages-${{ runner.os }}-

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: 10_preprod/.venv
          key: venv-tests-v3-${{ runner.os }}-py3.13-${{ hashFiles('10_preprod/uv.lock') }}

      - name: Install uv
        run: |
          if ! command -v uv &> /dev/null; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Install dependencies
        run: |
          cd 10_preprod
          # Créer un symlink /app/40_utils pour que le path absolu dans pyproject.toml fonctionne
          sudo mkdir -p /app
          sudo ln -s "$(pwd)/../40_utils" /app/40_utils
          if [ ! -d .venv ]; then
            uv venv
          fi
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run tests with coverage
        run: |
          cd 10_preprod
          source .venv/bin/activate
          echo "=== Exécution des tests avec couverture minimum 90% ==="
          pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=html --cov-fail-under=90

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-preprod
          path: 10_preprod/htmlcov/
          retention-days: 30

  infrastructure-tests:
    name: Tests d'infrastructure
    runs-on: ubuntu-latest
    needs: quality-checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache uv binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/uv
          key: uv-binary-${{ runner.os }}

      - name: Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-packages-${{ runner.os }}-${{ hashFiles('50_test/pyproject.toml', '50_test/uv.lock') }}
          restore-keys: |
            uv-packages-${{ runner.os }}-

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: 50_test/.venv
          key: venv-infra-v3-${{ runner.os }}-py3.13-${{ hashFiles('50_test/pyproject.toml') }}

      - name: Install uv
        run: |
          if ! command -v uv &> /dev/null; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Install test dependencies
        run: |
          cd 50_test
          if [ ! -d .venv ]; then
            uv venv
          fi
          source .venv/bin/activate
          uv pip install -e .

      - name: Run infrastructure tests
        run: |
          cd 50_test
          source .venv/bin/activate
          echo "=== Tests d'infrastructure (S3, DuckDB, Docker) ==="
          pytest -v -k "not test_docker" || echo "Some infrastructure tests may fail without credentials"
        continue-on-error: true  # Tests infra peuvent échouer sans credentials S3

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [quality-checks, test-preprod, infrastructure-tests]
    if: always()

    steps:
      - name: Check results
        run: |
          echo "=== Résumé du pipeline CI/CD ==="
          echo "Quality Checks: ${{ needs.quality-checks.result }}"
          echo "Tests Preprod: ${{ needs.test-preprod.result }}"
          echo "Tests Infrastructure: ${{ needs.infrastructure-tests.result }}"
          echo ""
          echo "ℹ️  Tests PROD désactivés (PROD = artifact généré par déploiement)"

          if [ "${{ needs.quality-checks.result }}" != "success" ] || \
             [ "${{ needs.test-preprod.result }}" != "success" ]; then
            echo "❌ Le pipeline CI a échoué"
            exit 1
          else
            echo "✅ Tous les tests sont passés avec succès"
          fi
